<?php
// Email notifications to be enable and triggered based on the MLR expiry date
// - 3 months prior expiry
// - 2 months prior expiry
// - 1 month prior expiry
// - Weekly from 1 month
// - And daily during last week
//for project gulf only

require_once __DIR__ . '/vendor/autoload.php';

use PHPMailer\PHPMailer\PHPMailer;
use GuzzleHttp\Client;
use GuzzleHttp\Exception\GuzzleException;


// Gmail SMTP configuration.
//$mail = new PHPMailer();
//$mail->isSMTP();
//$mail->Host = 'smtp.gmail.com';
//$mail->SMTPAuth = TRUE;
//$mail->Username = 'hany@orangestudio.com'; //paste one generated by Mailtrap
//$mail->Password = 'wcdwxnfswopizire'; //paste one generated by Mailtrap
//$mail->SMTPSecure = 'tls';
//$mail->Port = 587;

// Pfizer SMTP configuration.
$mail = new PHPMailer();
$mail->isSMTP();
$mail->Host = 'ndhsmtp.amer.pfizer.com';
$mail->SMTPAutoTLS = false;
$mail->Port = 25;

// Mail Headers.
$mail->setFrom('support.digicamp@pfizer.com', 'DigiCamp Support');
$mail->isHTML(TRUE);
$sent_messages_count = 0;

// Specify project ID = Gulf.
$project_id = 49;
$tracker_id = 6;
// Pfizer base URL.
$base_url = "http://digicamp.pfizer.com/";

// Local base URL.
//$base_url = "http://192.168.1.2/";

$issues_url = "issues.json?limit=100&project_id=$project_id&tracker_id=$tracker_id";
$users_url = "users/";
$username = "admin";
$password = "Pfizer@123";
$periods = [90, 60, 30, 21, 14];

try {
  $headers = [
    'Accept' => 'application/json',
    'Content-Type' => 'application/json',
  ];
  $httpClient = new Client();
  $response = $httpClient->request('GET', $base_url . $issues_url, [
    'headers' => $headers,
    'auth' => [$username, $password],
  ]);
  $data = $response->getBody()->getContents();
  $data = json_decode($data, TRUE);

  // Handling data offset.
  $loops = ceil($data['total_count'] / 100);

  for ($i = 0; $i < $loops; $i++) {
    $offset = $i * 100;
    $url = $base_url . $issues_url . "&offset=" . $offset;
    $response = $httpClient->request('GET', $url, [
      'headers' => $headers,
      'auth' => [$username, $password],
    ]);
    $data = $response->getBody()->getContents();
    $data = json_decode($data, TRUE);

    foreach ($data['issues'] as $issue) {
      $send = FALSE;
      $sendActionNeeded = FALSE;
      $cc = ['Diana.Shraim@pfizer.com','Kiran.Kulkarni@pfizer.com'];
      $cc2 = ['Diana.Shraim@pfizer.com','Kiran.Kulkarni@pfizer.com'];;
      foreach ($issue['custom_fields'] as $index => $field) {
        $field_name = $field["name"];
        if ($field["name"] == "Content Owner Name") {
          $name = $field["value"];
        }
        elseif ($field["name"] == "Content Owner Email") {
          $to = $field["value"];
          $cc2[] = $to;
        }
        elseif ($field["name"] == "Content is removed") {
          $removed = $field["value"];
        }
        elseif ($field["name"] == 'Content Owner Supervisor Email') {
          $cc[] = $field["value"];
          $cc2[] = $field["value"];
        }
        elseif ($field["name"] == "Content Expiration Date") {
          $expiry_date = $field["value"];
          $today = new DateTime("today");
          $expiry_date2 = new DateTime($expiry_date);
          $interval = $expiry_date2->diff($today);
          $diff_days = $interval->days;

          if ($expiry_date2 > $today && in_array($diff_days, $periods)) {
            $send = TRUE;
          }
          elseif ($expiry_date2 > $today && in_array($diff_days, [10])) {
            $sendActionNeeded = TRUE;
          }
          else {
            break;
          }
        }
        elseif ($field["name"] == "Gulf Content Mannager") {
          $gulf_manager = $field["id"];
          $response = $httpClient->request('GET', $base_url . $users_url . $gulf_manager . ".json", [
            'headers' => $headers,
            'auth' => [$username, $password],
          ]);
          $user_data = $response->getBody()->getContents();
          $user_data = json_decode($user_data, TRUE);
          if (!empty($user_data)) {
            $cc[] = $user_data['user']['mail'];
            $to2 = $user_data['user']['mail'];
          }

        }
//        elseif ($field["name"] == "Business Admin Email") {
//          $gulf_manager = $field["id"];
//          $response = $httpClient->request('GET', $base_url . $users_url . $gulf_manager . ".json", [
//            'headers' => $headers,
//            'auth' => [$username, $password],
//          ]);
//          $user_data = $response->getBody()->getContents();
//          $user_data = json_decode($user_data, TRUE);
//          if (!empty($user_data)) {
//            $cc[] = $user_data['user']['mail'];
//            $cc2[] = $user_data['user']['mail'];
//          }
//        }
      }

      if (isset($name, $to, $expiry_date) && (isset($removed) && !$removed)) {
        if ($send) {
          // Send email if all data is set.
          sendMail($name, $to, $diff_days, $issue["id"], $issue["subject"], $cc);
          $send = FALSE;
        }
        if ($sendActionNeeded && isset($to2)) {
          // Send email if all data is set.
          sendActionMail($name, $to2, $expiry_date, $issue["id"], $issue["subject"], $cc2);
          $sendActionNeeded = FALSE;
        }
      }
    }
  }

  echo $sent_messages_count . ' message(s) have been sent.';
  exit(0);
} catch (GuzzleException $e) {
  return $e->getMessage();
}

/*
 * Helper function to send email.
 */
function sendMail($name, $to, $expiry_date, $issue_id, $issue_subject, $cc = []) {
  $mail = $GLOBALS["mail"];
  $mail->addAddress($to, $name);
  if (!empty($cc)) {
    foreach ($cc as $item) {
      $mail->addCustomHeader("CC: {$item}");
    }
  }
  $mail->Subject = $issue_subject . ' - Content Expiration Notice';
  $mailContent = "
        Dear " . $name . ",<br>Your <a href='http://digicamp.pfizer.com/issues/" . $issue_id . "'>content</a> is expiring in " . $expiry_date . " days, if you do not renew or update material, you are giving consent for DCE to remove the content.
        <br><br>
        Best Regards,
        <br>
        DigiCamp Team";
  $mail->Body = $mailContent;
  if ($mail->send()) {
    $GLOBALS["sent_messages_count"]++;
  }
  else {
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
    exit(1);
  }
}

/*
 * Helper function to send email.
 */
function sendActionMail($name, $to, $expiry_date, $issue_id, $issue_subject, $cc = [])
{
  $mail = $GLOBALS["mail"];
  $mail->addAddress($to, $name);
  if (!empty($cc)) {
    foreach ($cc as $item) {
      $mail->addCustomHeader("CC: {$item}");
    }
  }
  $mail->Subject = "Action needed ; content removal from the Gulf Portal";
  $mailContent = "
        Dear " . $name . ",<br>Please remove this <a href='http://digicamp.pfizer.com/issues/" . $issue_id . "'>content</a> from the portal by $expiry_date.
        <br><br>
        Best Regards,
        <br>
        DigiCamp Team";
  $mail->Body = $mailContent;
  if ($mail->send()) {
    $GLOBALS["sent_messages_count"]++;
  } else {
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
    exit(1);
  }
}
